stages:
  data_ingestion:
    cmd: python src/Kidney_Disease_Classsification/pipeline/pipeline_stage01_data_ingestion.py
    deps:
      - src/Kidney_Disease_Classsification/pipeline/pipeline_stage01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone
    
  prepare_base_model:
    cmd: python src/Kidney_Disease_Classsification/pipeline/pipeline_stage02_base_model.py
    deps:
      - src/Kidney_Disease_Classsification/pipeline/pipeline_stage02_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/base_model/

  model_training:
    cmd: python src/Kidney_Disease_Classsification/pipeline/pipeline_stage03_model_training.py
    deps:
      - src/Kidney_Disease_Classsification/pipeline/pipeline_stage03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone
      - artifacts/base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/trained_model.keras

  evaluation:
    cmd: python src/Kidney_Disease_Classsification/pipeline/pipeline_stage04_model_evaluation.py
    deps:
      - src/Kidney_Disease_Classsification/pipeline/pipeline_stage04_model_evaluation.py
      - config/config.yaml
      - artifacts/training/trained_model.keras
      - artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false