artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1r-cNJnhO0APBZvIKxPiNId0RBqcNPNcI/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


model:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/model.keras
  updated_base_model_path: artifacts/base_model/updated_model.keras